### ISSUE TITLE
potential panic if servicaccount does not exist for run-pod

### ISSUE THREAD

**Issue by danj-replicated** [replicatedhq/troubleshoot#1442]
**Bug Description**

```
./support-bundle --load-cluster-specs default.yaml

failed to run collector: run-pod: failed to run pod: failed to create pod: pods "ekco-resources" is forbidden: error looking up service account kurl/ekco: serviceaccount "ekco" not found

panic: assignment to entry in nil map

```

**Expected Behavior**

not panic

**Steps To Reproduce**

Include the commands to reproduce the issue including any output. Any information that will help us to understand the problem is useful.  Feel free to paste long output into a [Github gist](https://gist.github.com) and include the link here.

**Additional Context**

Include the following information.
- Troubleshoot version. If you built from source, note that including the version of Go you used to build with.
- Operating system
- Operating system version
- Other details that might be helpful in diagnosing the problem

**Comment by diamonwiggins** [comment]
I've seen this a couple times now. We should prioritize @xavpaice 

edit. Actually the panic i'm seeing in a current support issue might not be exactly the same. Will have to investigate.

**Comment by adamancini** [comment]
I also ran into a panic with a similar output, troubleshoot 0.71.0;  I noticed there were a few run-pod collector pods that were stuck in ImagePullBackOff at the time the support bundle was taken.  Other than that I didn't notice anything out of the ordinary, but I'll try to see if I can repro.

```
kubectl support-bundle default2.yaml

panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/replicatedhq/troubleshoot/pkg/collect.CollectorResult.SaveResult(0xc0015c06e8?, {0xc000e49d80, 0x3f}, {0xc0013d2e40, 0x22}, {0x32099e0, 0xc000e40ab0})
        /home/runner/work/troubleshoot/troubleshoot/pkg/collect/result.go:113 +0xa8
github.com/replicatedhq/troubleshoot/pkg/collect.savePodDetails({0x32345d8, 0x4abbb40}, 0xc00132e680, 0x0?, {0xc000e49d80, 0x3f}, 0x1?, 0xc0008f2d80, 0xc0008b0000)
        /home/runner/work/troubleshoot/troubleshoot/pkg/collect/run_pod.go:433 +0x3ad
github.com/replicatedhq/troubleshoot/pkg/collect.(*CollectRunPod).Collect.func3()
        /home/runner/work/troubleshoot/troubleshoot/pkg/collect/run_pod.go:75 +0x51
github.com/replicatedhq/troubleshoot/pkg/collect.(*CollectRunPod).Collect(0xc0009610a0, 0x2b8c28b?)
        /home/runner/work/troubleshoot/troubleshoot/pkg/collect/run_pod.go:82 +0x773
github.com/replicatedhq/troubleshoot/pkg/supportbundle.runCollectors({0x3234808, 0xc000cf4150}, {0xc000cbc9a0?, 0x2b?, 0x4cbb05?}, 0xc000b0c000, {0xc000e49d80, 0x3f}, {0x2d07b00, 0x1, ...})
        /home/runner/work/troubleshoot/troubleshoot/pkg/supportbundle/collect.go:172 +0x1468
github.com/replicatedhq/troubleshoot/pkg/supportbundle.CollectSupportBundleFromSpec(0xc000581ca8, 0x4109a5?, {0x2d07b00, 0x1, 0x0, 0xc000ca98c0, {0x0, 0x0}, 0xc0000634a0, 0x0, ...})
        /home/runner/work/troubleshoot/troubleshoot/pkg/supportbundle/supportbundle.go:125 +0x7c9
github.com/replicatedhq/troubleshoot/cmd/troubleshoot/cli.runTroubleshoot(0x2b9accd?, {0xc00013bca0, 0x1, 0x1})
        /home/runner/work/troubleshoot/troubleshoot/cmd/troubleshoot/cli/run.go:182 +0xb34
github.com/replicatedhq/troubleshoot/cmd/troubleshoot/cli.RootCmd.func2(0xc000ad8f00?, {0xc00013bca0, 0x1, 0x1})
        /home/runner/work/troubleshoot/troubleshoot/cmd/troubleshoot/cli/root.go:47 +0x14d
github.com/spf13/cobra.(*Command).execute(0xc000ae9b00, {0xc000050150, 0x1, 0x1})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0xabc
github.com/spf13/cobra.(*Command).ExecuteC(0xc000ae9b00)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/replicatedhq/troubleshoot/cmd/troubleshoot/cli.InitAndExecute()
        /home/runner/work/troubleshoot/troubleshoot/cmd/troubleshoot/cli/root.go:99 +0x18
main.main()
        /home/runner/work/troubleshoot/troubleshoot/cmd/troubleshoot/main.go:9 +0xf
```

**Comment by nvanthao** [comment]
Similar issue is being seen with default cluster spec

```
./support-2/support-bundle --load-cluster-specs https://raw.githubusercontent.com/replicatedhq/troubleshoot-specs/main/in-cluster/default.yaml

panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/replicatedhq/troubleshoot/pkg/collect.CollectorResult.SaveResult(0xc000c486c8?, {0xc000c21c40, 0x3f}, {0xc000f25110, 0x22}, {0x3223900, 0xc000d45410})
/home/runner/work/troubleshoot/troubleshoot/pkg/collect/result.go:113 +0xa8
github.com/replicatedhq/troubleshoot/pkg/collect.savePodDetails({0x324e5a8, 0x4adaac0}, 0xc000c10680, 0x0?, {0xc000c21c40, 0x3f}, 0x1?, 0xc0009d5b00, 0xc000550280)
/home/runner/work/troubleshoot/troubleshoot/pkg/collect/run_pod.go:433 +0x3ad
github.com/replicatedhq/troubleshoot/pkg/collect.(*CollectRunPod).Collect.func3()
/home/runner/work/troubleshoot/troubleshoot/pkg/collect/run_pod.go:75 +0x51
github.com/replicatedhq/troubleshoot/pkg/collect.(*CollectRunPod).Collect(0xc0005cf340, 0x2ba3b3f?)
/home/runner/work/troubleshoot/troubleshoot/pkg/collect/run_pod.go:82 +0x773
github.com/replicatedhq/troubleshoot/pkg/supportbundle.runCollectors({0x324e7d8, 0xc000bd2900}, {0xc000a9cb00?, 0xab?, 0x50133b?}, 0xc00098de00, {0xc000c21c40, 0x3f}, {0x2d1fbd8, 0x1, ...})
/home/runner/work/troubleshoot/troubleshoot/pkg/supportbundle/collect.go:172 +0x1468
github.com/replicatedhq/troubleshoot/pkg/supportbundle.CollectSupportBundleFromSpec(0xc000bc62a8, 0x410bc5?, {0x2d1fbd8, 0x1, 0x0, 0xc0009de240, {0x0, 0x0}, 0xc000c316e0, 0x0, ...})
/home/runner/work/troubleshoot/troubleshoot/pkg/supportbundle/supportbundle.go:125 +0x7c9
github.com/replicatedhq/troubleshoot/cmd/troubleshoot/cli.runTroubleshoot(0x2bb25ef?, {0xc0009ac540, 0x1, 0x2})
/home/runner/work/troubleshoot/troubleshoot/cmd/troubleshoot/cli/run.go:182 +0xb34
github.com/replicatedhq/troubleshoot/cmd/troubleshoot/cli.RootCmd.func2(0xc0008d8d00?, {0xc0009ac540, 0x1, 0x2})
/home/runner/work/troubleshoot/troubleshoot/cmd/troubleshoot/cli/root.go:47 +0x14d
github.com/spf13/cobra.(*Command).execute(0xc0008ebb00, {0xc00010e610, 0x2, 0x2})
/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0xabc
github.com/spf13/cobra.(*Command).ExecuteC(0xc0008ebb00)
/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/replicatedhq/troubleshoot/cmd/troubleshoot/cli.InitAndExecute()
/home/runner/work/troubleshoot/troubleshoot/cmd/troubleshoot/cli/root.go:99 +0x18
main.main()
/home/runner/work/troubleshoot/troubleshoot/cmd/troubleshoot/main.go:9 +0xf
```

**Comment by nvanthao** [comment]
The panic happens here

https://github.com/replicatedhq/troubleshoot/blob/f6373f3e36d6cef7bb30e589bf96deb65b185742/pkg/collect/result.go#L113

but it is unclear to me why it is nil since we did initialize it earlier
https://github.com/replicatedhq/troubleshoot/blob/3012b870bda3af1d22eee4f320adb939b3cc9d7d/pkg/collect/run_pod.go#L49

**Comment by banjoh** [comment]
> but it is unclear to me why it is nil since we did initialize it earlier

The reason we panic is cause [this deferred call](https://github.com/replicatedhq/troubleshoot/blob/ebe98ff2f1292638acb8413e9f7f3e729b1940da/pkg/collect/run_pod.go#L74-L79) will always run when the parent function (`(*CollectRunPod).Collect(...)`)  returns. Now, if the parent function exits with `nil, error`, say [here](https://github.com/replicatedhq/troubleshoot/blob/ebe98ff2f1292638acb8413e9f7f3e729b1940da/pkg/collect/run_pod.go#L87) or [here (which is the cause of the panic we are seeing)](https://github.com/replicatedhq/troubleshoot/blob/ebe98ff2f1292638acb8413e9f7f3e729b1940da/pkg/collect/run_pod.go#L82), `savePodDetails` will receive a `result` parameter equal to `nil`. The first call to use this parameter (`output`) which is [here](https://github.com/replicatedhq/troubleshoot/blob/ebe98ff2f1292638acb8413e9f7f3e729b1940da/pkg/collect/run_pod.go#L433) will panic.

We'd need to check whether there was a prior error before trying to call `savePodDetails`

```go
defer func() {
	if err != nil {
		return
	}
	result, err = savePodDetails(ctx, client, result, c.BundlePath, c.ClientConfig, pod, c.Collector)
	if err != nil {
		klog.Errorf("failed to save pod details: %v", err)
	}
}()
```

**Comment by nvanthao** [comment]
Many thanks @banjoh let me update the fix!
