### ISSUE TITLE
panic: runtime error: index out of range when using textAnalyze

### ISSUE THREAD

**Issue by aj-jester** [replicatedhq/troubleshoot#169]
```
$ kubectl preflight version
Replicated Preflight 0.9.28
```

Attaching the relevant yaml spec
[preflight.txt](https://github.com/replicatedhq/troubleshoot/files/4453591/preflight.txt)

```
$ kubectl preflight preflight.yaml
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/replicatedhq/troubleshoot/pkg/analyze.analyzeRegexGroups(0xc000088c40, 0x6f, 0xc00068a000, 0x19b, 0x19b, 0xc00034a5f0, 0x2
, 0x2, 0xc0005db030, 0x8, ...)
        /home/runner/work/troubleshoot/troubleshoot/pkg/analyze/text_analyze.go:94 +0x982
github.com/replicatedhq/troubleshoot/pkg/analyze.analyzeTextAnalyze(0xc0004bd830, 0xc0004cc340, 0x0, 0x0, 0x0)
        /home/runner/work/troubleshoot/troubleshoot/pkg/analyze/text_analyze.go:30 +0x27c
github.com/replicatedhq/troubleshoot/pkg/analyze.Analyze(0xc000568700, 0xc0004cc340, 0xc0004cc3c0, 0x0, 0x0, 0x0)
        /home/runner/work/troubleshoot/troubleshoot/pkg/analyze/analyzer.go:158 +0x433
github.com/replicatedhq/troubleshoot/pkg/preflight.CollectResult.Analyze(0xc000644030, 0xc000642300, 0x3, 0x4, 0x0, 0xc0000cc9a0, 0xc
000644030, 0xc000642300, 0x3)
        /home/runner/work/troubleshoot/troubleshoot/pkg/preflight/analyze.go:33 +0x184
github.com/replicatedhq/troubleshoot/cmd/preflight/cli.runPreflights(0xc0000d8300, 0x7ffca73fd6da, 0xe, 0x0, 0x0)
        /home/runner/work/troubleshoot/troubleshoot/cmd/preflight/cli/run.go:123 +0x9e6
github.com/replicatedhq/troubleshoot/cmd/preflight/cli.RootCmd.func2(0xc00039c500, 0xc00027c4e0, 0x1, 0x1, 0x0, 0x0)
        /home/runner/work/troubleshoot/troubleshoot/cmd/preflight/cli/root.go:29 +0x4e
github.com/spf13/cobra.(*Command).execute(0xc00039c500, 0xc00000c0b0, 0x1, 0x1, 0xc00039c500, 0xc00000c0b0)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x465
github.com/spf13/cobra.(*Command).ExecuteC(0xc00039c500, 0x0, 0x0, 0x17d7fe8)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/replicatedhq/troubleshoot/cmd/preflight/cli.InitAndExecute()
        /home/runner/work/troubleshoot/troubleshoot/cmd/preflight/cli/root.go:57 +0x28
main.main()
        /home/runner/work/troubleshoot/troubleshoot/cmd/preflight/main.go:9 +0x20
```

**Comment by marccampbell** [comment]
Including the YAML here so we don't lose it:

```
apiVersion: troubleshoot.replicated.com/v1beta1
kind: Preflight
metadata:
  name: sentry-enterprise
spec:
  analyzers:
    - textAnalyze:
        checkName: "run-ping"
        fileName: ping/run-ping.log
        data: '{{repl ConfigOption "replica_count" }}'
        regexGroups: '(?P<Transmitted>\d+) packets? transmitted, (?P<Received>\d+) packets? received, (?P<Loss>\d+\.\d+)% packet loss'
        outcomes:
          - pass:
              when: "Loss < 5.0"
              message: Solid connection to google.com
          - fail:
              message: High packet loss
    - deploymentStatus:
        name: sentry-worker
        outcomes:
          - fail:
              when: "< 1"
              message: The Sentry Worker deployment does not have any ready replicas.
          - warn:
              when: "= 1"
              message: The Sentry Worker deployment has only a single ready replica.
          - pass:
              message: There are multiple replicas of the Sentry Worker deployment ready.
    - clusterVersion:
        outcomes:
          - fail:
              when: "< 1.13.0"
              message: Sentry requires at Kubernetes 1.13.0 or later, and recommends 1.15.0.
              uri: https://www.kubernetes.io
          - warn:
              when: "< 1.15.0"
              message: Your cluster meets the minimum version of Kubernetes, but we recommend you update to 1.15.0 or later.
              uri: https://kubernetes.io
          - pass:
              when: ">= 1.15.0"
              message: Your cluster meets the recommended and required versions of Kubernetes.
    - customResourceDefinition:
        customResourceDefinitionName: ingressroutes.contour.heptio.com
        outcomes:
          - fail:
              message: IngressRoutes CRD not found!
          - pass:
              message: IngressRoutes CRD found!
    - containerRuntime:
        outcomes:
          - pass:
              when: "== docker"
              message: Docker container runtime was found.
          - fail:
              message: Did not find Docker container runtime.
    - storageClass:
        checkName: Required storage classes
        storageClassName: "default"
        outcomes:
          - fail:
              message: Could not find a storage class called default.
          - pass:
              message: All good on storage classes
    - distribution:
        outcomes:
          - fail:
              when: "== docker-desktop"
              message: The application does not support Docker Desktop Clusters
          - fail:
              when: "== microk8s"
              message: The application does not support Microk8s Clusters
          - fail:
              when: "== minikube"
              message: The application does not support Minikube Clusters
          - pass:
              when: "== eks"
              message: EKS is a supported distribution
          - pass:
              when: "== gke"
              message: GKE is a supported distribution
          - pass:
              when: "== aks"
              message: AKS is a supported distribution
          # Will be supported in the future
          - pass:
              when: "== kurl"
              message: KURL is a supported distribution
          - pass:
              when: "== digitalocean"
              message: DigitalOcean is a supported distribution
          - warn:
              message: Unable to determine the distribution of Kubernetes
    - nodeResources:
        checkName: Must have at least 3 nodes in the cluster
        outcomes:
        - fail:
            when: "count() < 3"
            message: This application requires at least 3 nodes.
            uri: https://kurl.sh/docs/install-with-kurl/adding-nodes
        - warn:
            when: "count() < 5"
            message: This application recommends at last 5 nodes.
            uri: https://kurl.sh/docs/install-with-kurl/adding-nodes
        - pass:
            message: This cluster has enough nodes.
    - nodeResources:
        checkName: Every node in the cluster must have at least 32Gi of memory
        outcomes:
        - fail:
            when: "min(memoryCapacity) < 10Gi"
            message: All nodes must have at least 10 GB of memory.
            uri: https://kurl.sh/docs/install-with-kurl/system-requirements
        - warn:
            when: "min(memoryCapacity) < 32Gi"
            message: All nodes are recommended to have at least 32 GB of memory.
            uri: https://kurl.sh/docs/install-with-kurl/system-requirements
        - pass:
            message: All nodes have at least 32 GB of memory.
    - nodeResources:
        checkName: Total CPU Cores in the cluster is 4 or greater
        outcomes:
          - fail:
              when: "sum(cpuCapacity) < 4"
              message: The cluster must contain at least 4 cores
              uri: https://kurl.sh/docs/install-with-kurl/system-requirements
          - pass:
              message: There are at least 4 cores in the cluster
    - nodeResources:
        checkName: Every node in the cluster must have at least 40 GB of ephemeral storage
        outcomes:
        - fail:
            when: "min(ephemeralStorageCapacity) < 40Gi"
            message: All nodes must have at least 40 GB of ephemeral storage.
            uri: https://kurl.sh/docs/install-with-kurl/system-requirements
        - warn:
            when: "min(ephemeralStorageCapacity) < 100Gi"
            message: All nodes are recommended to have at least 100 GB of ephemeral storage.
            uri: https://kurl.sh/docs/install-with-kurl/system-requirements
        - pass:
            message: All nodes have at least 100 GB of ephemeral storage.
  collectors:
    - run:
        collectorName: "run-ping"
        image: busybox:1
        name: ping
        namespace: default
        command: ["ping"]
        args: ["-w", "5", "4.2.2.2"]
        imagePullPolicy: IfNotPresent
```

**Comment by matias-manavella-nimble** [comment]
@marccampbell Hi Marc, this issue was fixed in the following [commit](https://github.com/replicatedhq/troubleshoot/commit/09bc81e14499c5e1c129afd634e1fa64ec4b8ec2), which I tracked to the PR https://github.com/replicatedhq/troubleshoot/pull/181. This issue should be closed.
```shell
commit 09bc81e14499c5e1c129afd634e1fa64ec4b8ec2
Author: Andrew Lavery <laverya@umich.edu>
Date:   Thu Apr 23 15:26:01 2020 -0400

    analyzeRegexGroups should not have out of range error upon no match
```
